version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

  php:
    build: ./docker/php
    container_name: php
    restart: always
    volumes:
      - ./:/var/www
    env_file: ./.env
    networks:
      - default
    php-queue:
      build: ./docker/php
      container_name: php-queue
      restart: always
      entrypoint:
        - 'php'
        - 'artisan'
        - 'queue:work'
        - '--tries=3'
      volumes:
        - ./:/var/www
      env_file: ./.env
      networks:
        - default
    php-schedule:
      build: ./docker/php
      container_name: php-schedule
      restart: always
      volumes:
        - ./:/var/www
      env_file: ./.env
      networks:
        - default

  mysql:
    image: mariadb
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: masaqiao9
    restart: always
    networks:
      - default
networks:
  default:
    external:
      name: project_default
